### ISSUE TITLE
Crash on getMessageHandler()

### ISSUE THREAD

**Issue by scalagos0123** [Nekland/Woketo#149]
Using v2.2, Websocket crashes when I call the URI to my websocket. I've set up SSL to use WSS.

First few lines of the error stack:
`
Type error: Argument 1 passed to Nekland\Woketo\Server\WebSocketServer::getMessageHandler() must be of the type string, null given, called in /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php on line 162 in /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php:208
Stack trace:
#0 /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Server/WebSocketServer.php(162): Nekland\Woketo\Server\WebSocketServer->getMessageHandler(NULL, Object(Nekland\Woketo\Server\Connection))
#1 /mnt/c/Users/HTECH-Shaun/projects/shareapi/vendor/nekland/woketo/src/Core/AbstractConnection.php(147): Nekland\Woketo\Server\WebSocketServer->Nekland\Woketo\Server\{closure}(NULL, Object(Nekland\Woketo\Server\Connection))
`

This is my instance:

```
private $connConfig = [
        'ssl' => true,
        'certFile' => '/etc/apache2/ssl/apache.pem',
        'sslContextOptions' => [
            'verify_peer' => false,
            'allow_self_signed' => true
        ]
 ];

$server = new WebSocketServer(8080, '127.0.2.1', $this->connConfig);
$server->setMessageHandler(new WebsocketWoketo(), '/ivm');
$server->start();
```

**Comment by Nek-** [comment]
Hello, thanks for the report. This is a real issue. Gonna work on it right now.

But please notice that this is due because of early disconnection of the client (understand before handshake occurs, which means probably certificate issue).

**Comment by scalagos0123** [comment]
Thank you very much! Will test this immediately.
