### ISSUE TITLE
WebSocket connection gets broken after some time

### ISSUE THREAD

**Issue by DonatasStoncius** [Nekland/Woketo#154]
I have an issue that I can't pinpoint. After 10-60min of idle time the WebSocket gets broken. Server part of the WebSocket (not Woketo) notices that, but there's no log or Exception. It feels like the package doesn't know that the WebSocket connection is broken and doesn't do anything about it. Did you encounter this issue? Any tips on how to maybe trigger a PING over the WebSocket as it should help keep the socket open? Or maybe there's some other way to sense that the WebSocket was closed? From the WebSocket server part it looks like the WebSocket is being terminated on Woketo part.

**Comment by Nek-** [comment]
Sorry for late answer. Maybe you're using some kind of networking with timeout on idle connections?

Did you find out why it happens? Any HAProxy or something?

**Comment by Nek-** [comment]
Closing since it's probably not related to Woketo itself and no news from the author.
