### ISSUE TITLE
Woketo Client

### ISSUE THREAD

**Issue by Nek-** [Nekland/Woketo#87]
Woketo is a server. Great. What about having it as client ?

**Comment by Nek-** [comment]
This issue is plan for 2.0 as there is some BC Break inside and almost nobody uses the 1.0 :) .

**Comment by quarkmarino** [comment]
Any idea on when it would be available?

**Comment by Nek-** [comment]
@quarkmarino there's already some work there: https://github.com/Nekland/Woketo/pull/100

I plan to finish it before the end of June. 😉
